server:
  port: 8082
  servlet:
    context-path: /rasplus

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RASPLUS
    username: rasmoo
    password: senha123
  flyway:
    enabled: true

springdoc:
  packagesToScan: com.client.api.rasplus.controller

webservice:
  raspay:
    host: ${RASPAY_HOST:http://localhost:8081/ws-raspay}
    customer: ${RASPAY_CUSTOMER:/v1/customer}
    order: ${RASPAY_ORDER:/v1/order}
    payment: ${RASPAY_PAYMENT:/v1/payment/credit-card}