server:
  port: 8082
  servlet:
    context-path: /rasplus

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RASPLUS
    username: rasmoo
    password: senha123
  flyway:
    enabled: true

springdoc:
  packagesToScan: com.client.api.rasplus.controller